apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-nfs-media
  namespace: jellyfin
spec:
  storageClassName: nfs-csi
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/Media
    server: 192.168.x.x
    readOnly: false
