---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-10gb-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: mysql-10gb-nfs
  storageClassName: nfs-csi
