apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
spec:
  type: LoadBalancer
  ports:
  - name: mysql-tcp
    port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: uptime-kuma
