kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: uptime-kuma-10gb-smb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: uptime-kuma-10gb-smb
  storageClassName: smb
