apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc-media
  namespace: jellyfin
spec:
  storageClassName: nfs-csi
  volumeName: jellyfin-pv-nfs-media
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Ti
