kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: minecraft
  storageClassName: smb