apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  type: NodePort
  ports:
  - name: minecraft-rcon
    port: 25565
    targetPort: 25565
    protocol: TCP
  selector:
    app: minecraft
